# Generated by Django 2.2.6 on 2019-11-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('current_ctc', models.IntegerField()),
                ('expected_ctc', models.IntegerField()),
                ('notice_period', models.IntegerField()),
            ],
        ),
    ]
